### ISSUE TITLE
你好，这个工程没有实现汽车同步相关的代码么

### ISSUE THREAD

**Issue by justinlm** [light-and-salt/CarRacingGame#1]
如题：你好，这个工程没有实现汽车同步相关的代码么。最近我在做汽车位置同步这块。所以问下

**Comment by light-and-salt** [comment]
应该是有的： 
1. https://github.com/ZeningQu/CarRacingGame/tree/master/Assets/Scripts/Sync
2. https://github.com/ZeningQu/CarRacingGame/tree/master/Assets/Plugins

1 是同步代码
2 是一些把 CCN 的 C 代码转化为 Unity 插件的代码，以便让 1 能使用

这个项目是我好几年前做的啦，现在的 Unity 和 CCN/NDN API 应该有很大变化了

**Comment by justinlm** [comment]
好的，非常感谢。
